import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://placeholder-supabase-url.co';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'placeholder-anon-key';

if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
  if (typeof window === 'undefined') {
    console.warn(
      'Supabase environment variables (NEXT_PUBLIC_SUPABASE_URL / NEXT_PUBLIC_SUPABASE_ANON_KEY) are not set. Database operations will fail.'
    );
  }
}

/**
 * Default standard Supabase client for authenticated users.
 * Automatically utilizes Clerk/Swipbase session tokens when called on the client.
 */
export const supabase = createClient(supabaseUrl, supabaseAnonKey);

/**
 * Returns a customized Supabase client.
 * 
 * If a `shareToken` is provided (e.g., in a manager public view route), it injects
 * the `x-share-token` header into the global headers. Supabase's Postgres Row-Level
 * Security (RLS) rules read this header to grant read-only access to anon requests.
 * 
 * @param shareToken Secure UUID token generated by the designer.
 */
export function getSupabaseClient(shareToken?: string) {
  if (!shareToken) {
    return supabase;
  }

  const url = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://placeholder-supabase-url.co';
  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'placeholder-anon-key';

  return createClient(url, key, {
    global: {
      headers: {
        'x-share-token': shareToken,
      },
    },
    auth: {
      persistSession: false, // Do not store auth state for anonymous managers
    },
  });
}
export type SupabaseClientType = ReturnType<typeof getSupabaseClient>;

const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';

/**
 * Privileged admin client bypassing Row-Level Security.
 * Kept strictly on the server-side to prevent exposing the service key to the client.
 */
export const supabaseAdmin = typeof window === 'undefined' && supabaseServiceKey
  ? createClient(supabaseUrl, supabaseServiceKey, {
      auth: {
        persistSession: false,
        autoRefreshToken: false,
      },
    })
  : supabase;
