import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseAnonKey) {
  if (typeof window === 'undefined') {
    console.warn(
      'Supabase environment variables (NEXT_PUBLIC_SUPABASE_URL / NEXT_PUBLIC_SUPABASE_ANON_KEY) are not set. Database operations will fail.'
    );
  }
}

/**
 * Default standard Supabase client for authenticated users.
 * Automatically utilizes Clerk/Supabase session tokens when called on the client.
 */
export const supabase = createClient(supabaseUrl, supabaseAnonKey);

/**
 * Returns a customized Supabase client.
 * 
 * If a `shareToken` is provided (e.g., in a manager public view route), it injects
 * the `x-share-token` header into the global headers. Supabase's Postgres Row-Level
 * Security (RLS) rules read this header to grant read-only access to anon requests.
 * 
 * @param shareToken Secure UUID token generated by the designer.
 */
export function getSupabaseClient(shareToken?: string) {
  if (!shareToken) {
    return supabase;
  }

  return createClient(supabaseUrl, supabaseAnonKey, {
    global: {
      headers: {
        'x-share-token': shareToken,
      },
    },
    auth: {
      persistSession: false, // Do not store auth state for anonymous managers
    },
  });
}
export type SupabaseClientType = ReturnType<typeof getSupabaseClient>;
